apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../shared
  - deployment.yaml

configMapGenerator:
  - name: open5gs-upf-config
    files:
      - configs/upf-quic.yaml

images:
  - name: open5gs-webui
    newName: localhost:5001/open5gs-webui
    newTag: latest
  - name: open5gs-run
    newName: localhost:5001/ubuntu-24.04-open5gs-run
    newTag: latest
