include:
  - path: compose/open5gs.yaml
  - path: compose/ueransim.yaml
  - path: compose/logs.yaml

networks:
  shared_network:
    name: shared_network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.name: br-open5gs
    ipam:
      config:
        - subnet: 10.10.0.0/16
  99-ghost-in-da-edge:
    name: ghost-in-da-edge
    internal: false
