services:
  mongodb:
    image: mongo
    container_name: open5gs-mongodb
    restart: unless-stopped
    networks:
      shared_network:
        ipv4_address: 10.10.0.2
    volumes:
      - mongodb:/data/db
      - ./open5gs/docs/assets/webui/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro,Z
    environment:
      - MONGO_INITDB_DATABASE=open5gs
    command: mongod --bind_ip 0.0.0.0 --port 27018

  webui:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.open5gs.webui
    image: ${USER}/open5gs-webui
    container_name: open5gs-webui
    environment:
      - DB_URI=mongodb://10.10.0.2:27018/open5gs
      - WAIT_HOSTS=10.10.0.2:27018
    networks:
      shared_network:
        ipv4_address: 10.10.0.3

  base:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.base
      args:
        dist: ${DIST-ubuntu}
        tag: ${TAG-latest}
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-base
    restart: unless-stopped
    command: /bin/bash -c "echo 'base' services && sleep infinity"

  run:
    depends_on:
      - mongodb
      - base
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.open5gs.run
      args:
        dist: ${DIST-ubuntu}
        tag: ${TAG-latest}
        username: ${USER}
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-open5gs-run
    restart: unless-stopped
    networks:
      shared_network:
        ipv4_address: 10.10.0.10
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    container_name: open5gs-run
    hostname: open5gs-run
    volumes:
      - ./open5gs-config:/usr/local/etc/open5gs:Z
    environment:
      - DB_URI=mongodb://10.10.0.2:27018/open5gs
    command: >
      /bin/bash -c "
      /wait &&
      /root/setup.sh &&
      open5gs-nrfd -D && sleep 2 &&
      open5gs-scpd -D && sleep 2 &&
      open5gs-amfd -D &&
      open5gs-smfd -D &&
      open5gs-upfd -D &&
      open5gs-ausfd -D &&
      open5gs-udmd -D &&
      open5gs-pcfd -D &&
      open5gs-nssfd -D &&
      open5gs-bsfd -D &&
      open5gs-udrd -D &&
      sleep infinity
      "

  ueransim-gnb:
    depends_on:
      - run
      - base
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.ueransim
      args:
        dist: ${DIST-ubuntu}
        tag: ${TAG-latest}
        username: ${USER}
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-ueransim-gnb
    privileged: true
    container_name: ueransim-gnb
    restart: unless-stopped
    networks:
      shared_network:
        ipv4_address: 10.10.0.4
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./ueransim-config:/ueransim/config:Z
    environment:
      - AMF_HOSTNAME=10.10.0.10
    command: /bin/bash -c "sleep 10 && build/nr-gnb -c /ueransim/config/open5gs-gnb.yaml"

  ueransim-ue:
    depends_on:
      - run
      - base
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.ueransim
      args:
        dist: ${DIST-ubuntu}
        tag: ${TAG-latest}
        username: ${USER}
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-ueransim-ue
    container_name: ueransim-ue
    privileged: true
    restart: unless-stopped
    networks:
      shared_network:
        ipv4_address: 10.10.0.16
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - GNB_HOSTNAME=10.10.0.4
    volumes:
      - ./ueransim-config:/ueransim/config:Z
    command: /bin/bash -c "sleep 15 && build/nr-ue -c /ueransim/config/open5gs-ue.yaml"

volumes:
  mongodb: {}

networks:
  shared_network:
    name: shared_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
