kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: phonson-cluster
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
      endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=open5gs-services"
            allowed-unsafe-sysctls: "net.ipv4.ip_forward"

    extraPortMappings:
      - containerPort: 38412
        hostPort: 38412
        protocol: SCTP

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=open5gs-subscriber-db"

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=open5gs-gtpu-upf"
            allowed-unsafe-sysctls: "net.ipv4.ip_forward"
    extraPortMappings:
      - containerPort: 2152
        hostPort: 2152
        protocol: UDP

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=open5gs-webui"
    extraPortMappings:
      - containerPort: 9999
        hostPort: 9999
        protocol: TCP
