kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: phonton-cluster
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
      endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
    extraMounts:
      - hostPath: /usr/libexec/cni/
        containerPath: /opt/cni/bin/

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=ueransim-gnb-gtpu"
    extraMounts:
      - hostPath: /usr/libexec/cni/
        containerPath: /opt/cni/bin/

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=ueransim-ue-gtpu"
    extraMounts:
      - hostPath: /usr/libexec/cni/
        containerPath: /opt/cni/bin/

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=ueransim-gnb-quic"
    extraMounts:
      - hostPath: /usr/libexec/cni/
        containerPath: /opt/cni/bin/

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "tier=ueransim-ue-quic"
    extraMounts:
      - hostPath: /usr/libexec/cni/
        containerPath: /opt/cni/bin/
