apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ../shared

configMapGenerator:
  - name: ueransim-gnb-config
    files:
      - open5gs-gnb.yaml=configs/open5gs-gnb-gtpu.yaml

  - name: ueransim-ue-config
    files:
      - open5gs-ue.yaml=configs/open5gs-ue-gtpu.yaml
