apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../shared
  - deployment.yaml

configMapGenerator:
  - name: ueransim-gnb-config
    files:
      - open5gs-gnb.yaml=configs/open5gs-gnb-quic.yaml

  - name: ueransim-ue-config
    files:
      - open5gs-ue.yaml=configs/open5gs-ue-quic.yaml
