{{- if .Values.quic.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-gnb-quic-config
data:
  open5gs-gnb.yaml: |
{{.Files.Get "configs/ran/quic/open5gs-gnb-quic.yaml" | indent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-ue-quic-config
data:
  open5gs-ue.yaml: |
{{.Files.Get "configs/ran/quic/open5gs-ue-quic.yaml" | indent 4}}
{{- end }}
