apiVersion: v1
kind: ConfigMap
metadata:
  name: { { .Values.gnb.config_map_name } }
data:
  open5gs-gnb.yaml: |
    {{ .Files.Get .Values.gnb.config_path | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: { { .Values.ue.config_map_name } }
data:
  open5gs-ue.yaml: |
    {{ .Files.Get .Values.ue.config_path | indent 4 }}
