logger:
  file:
    path: /var/local/log/open5gs/upf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024 # The number of UE can be increased depending on memory size.
#    peer: 64

upf:
  pfcp:
    server:
      - address: 10.10.0.13
    client:
  #      smf:     #  UPF PFCP Client try to associate SMF PFCP Server
  #        - address: 127.0.0.4

  transport_mode: gtpu
  quic:
    address: 127.0.0.1
    cert: /secrets/server.crt
    key: /secrets/server.key

  gtpu:
    server:
      - address: 172.23.0.13

  session:
    - subnet: 10.47.0.0/16
      gateway: 10.47.0.1
      dnn: ipsec-net
    - subnet: 2001:db8:cafe::/48
      gateway: 2001:db8:cafe::1
  metrics:
    server:
      - address: 10.10.0.13
        port: 9090

################################################################################
