apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../shared
  - deployment.yaml

configMapGenerator:
  - name: open5gs-upf-config
    files:
      - configs/upf-quic.yaml
