apiVersion: v1
kind: Secret
metadata:
  name: open5gs-core-secrets
type: Opaque
data:
  server.key: |
    {{ .Files.Get "secrets/server.key" | b64enc }}
  server.crt: |
    {{ .Files.Get "secrets/server.crt" | b64enc }}
