apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ../nads

configMapGenerator:
  - name: ueransim-gnb-config
    files:
      - configs/open5gs-gnb-gtpu.yaml

  - name: ueransim-ue-config
    files:
      - configs/open5gs-ue-gtpu.yaml

images:
  - name: ueransim-gnb
    newName: localhost:5001/ubuntu-24.04-ueransim-gnb
    newTag: latest
  - name: ueransim-ue
    newName: localhost:5001/ubuntu-24.04-ueransim-ue
    newTag: latest
