config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=yes

conn gtpu-tunnel
    type=tunnel
    authby=secret
    left=10.10.0.6          # gNB-gtpu-ipsec Local IP
    leftsubnet=10.10.0.6/32
    right=10.10.0.13        # UPF-gtpu-ipsec Remote IP
    rightsubnet=10.10.0.13/32
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    keyexchange=ikev2
    auto=start              # Script calls 'ipsec up' explicitly
